### ISSUE TITLE
Can you check for acceptance?

### ISSUE THREAD

**Issue by Zackhardtoname** [rsb-23/1page-automation#1]
The LC solution might be incorrect and we should check. Appreciate it!

**Comment by rsb-23** [comment]
Can you please test the changes from [Acceptance check](https://github.com/rsb-23/1page-automation/tree/1-add-acceptance-check) branch?
I'll merge to main branch once it works for you.

**Comment by Zackhardtoname** [comment]
Yep it worked!

**Comment by Zackhardtoname** [comment]
I suggest this
```Python
    resp = check()
    while resp["state"] != "SUCCESS":
        sleep(0.5)
        resp = check()
```

**Comment by rsb-23** [comment]
Its not a good practice to make function call twice in this case.
