### ISSUE TITLE
[Leetcode] The submission request results in 403

### ISSUE THREAD

**Issue by Zackhardtoname** [rsb-23/1page-automation#3]
I tried updating the cookies to be exactly the same as the network request, but it's still 403. If I copy the network request as curl, it does succeed.

I am pretty stuck at this moment and would love some help 💜

**Comment by Zackhardtoname** [comment]
I can't really share the curl since it contains all my cookies. I modified the log a bit in myself but did isolate the problem to be the submission request returning 403.

[This is the question](https://leetcode.com/problems/minimum-number-of-visited-cells-in-a-grid/solutions/3395709/c-java-python3-set-treeset-sortedlist-bfs/
). 

I just used the solution [here](https://github.com/doocs/leetcode/blob/main/solution/2600-2699/2617.Minimum%20Number%20of%20Visited%20Cells%20in%20a%20Grid/Solution.py). The language is Python.

**Comment by rsb-23** [comment]
check [request header](https://github.com/rsb-23/1page-automation/pull/4/files#diff-d729f5cb03523121bc9cde8ced56ea898f8a8936f89d56693fbddb7f01ec6e36R98) line 98

**Comment by Zackhardtoname** [comment]
It works now... The weird thing is that once I got the submission to be accepted with your changes, the script after reverting all your latest changes works again... Not sure why.

**Comment by rsb-23** [comment]
- It works for limited time period due to caching either at client or server side.
- Check https://newrelic.com

**Comment by Zackhardtoname** [comment]
I assume that's just something you use to track usage of the code here :)

**Comment by rsb-23** [comment]
🫨 Just checked, they have modified the logic. `Newrelic id` was part of request header inplace of `uuserid`.

FYI, there are no trackers in my code. 🙏🏼

**Comment by Zackhardtoname** [comment]
Ah that makes sense now
